name: pg
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10.1 # Compatibility with Planetary Computer Base Install
  - attrs==21.2.0
  - bcrypt>=4.0.0
  - cached-property==1.5.2
  - certifi>=2021.5.30
  - cffi==1.15.1
  - chardet==4.0.0
  - charset-normalizer==3.1.0
  - click==7.1.2
  - click-plugins==1.1.1
  - cligj==0.7.2
  - colorama==0.4.6
  - commonmark==0.9.1
  - cryptography==37.0.4
  - cycler==0.10.0
  - dirsync>=2.2.4
  - impactutils==0.8.40
  - Fiona>=1.8.19
  - geographiclib==2.0
  - geopy==2.4.1
  - h5py==3.4.0
  - hdf5storage>=0.1.18
  - idna==2.10
  - joblib==1.0.1
  - libcomcat==2.0.10
  - matplotlib>=2.0.0
  - munch==2.5.0
  - netifaces==0.10.9
  - numpy==1.21.6
  - openpyxl==3.0.7
  - pandas==1.4.1
  - paramiko==2.11.0
  - psutil>=5.6.3
  - pycparser==2.21
  - Pygments==2.14.0
  - PyJWT==2.6.0
  - PyNaCl==1.5.0
  - pyparsing==2.4.7
  - pysftp==0.2.9
  - python-dateutil==2.8.2
  - pytz==2021.1
  - requests==2.28.2
  - rich==12.6.0
  - scandir>=1.6
  - scikit-learn>=1.1
  - scipy>=1.2.0
  - Shapely>=1.7.1
  - shellingham==1.5.0.post1
  - simplekml==1.3.1
  - six==1.16.0
  - threadpoolctl==2.2.0
  - tqdm==4.66.5
  - typer==0.7.0
  - typing_extensions==4.5.0
  - urllib3==1.26.6
  - xmltodict==0.13.0
  - pip
  - pip:
    - overcluster
    - pycos
    - dispy #==4.15.2
    - PyGreSQL==5.2.5
    - country-converter #>=1.2
    - et-xmlfile #>=1.1.0
    - earthscope-cli==0.8.2
    - earthscope-sdk==0.2.0
