[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "pgamit"
dynamic = ["version"]
# more missing

[tool.setuptools_scm]
version_file = "pgamit/_version.py"

